# Generated by Django 5.2.7 on 2026-04-05 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "execution_mode",
                    models.CharField(
                        choices=[
                            ("draft_only", "Draft only"),
                            ("confirm", "Confirm before executing"),
                            ("auto", "Auto"),
                        ],
                        default="draft_only",
                        max_length=32,
                    ),
                ),
                ("blocked_times", models.JSONField(blank=True, default=list)),
                ("email_send_limit_per_hour", models.PositiveIntegerField(default=20)),
                ("event_create_limit_per_hour", models.PositiveIntegerField(default=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "preferences_user_preferences",
            },
        ),
    ]
