# Generated by Django 6.0.3 on 2026-04-04 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Calendar",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("google_calendar_id", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("is_primary", models.BooleanField(default=False)),
                ("color", models.CharField(blank=True, max_length=32)),
                ("sync_token", models.TextField(blank=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendars",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "calendars_calendar",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "google_calendar_id"),
                        name="calendars_calendar_user_google_calendar_id_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("google_event_id", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("timezone", models.CharField(blank=True, max_length=64)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("status", models.CharField(blank=True, max_length=32)),
                ("attendees", models.JSONField(blank=True, default=list)),
                ("organizer_email", models.EmailField(blank=True, max_length=254)),
                ("is_all_day", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="calendars.calendar",
                    ),
                ),
            ],
            options={
                "db_table": "calendars_event",
                "indexes": [
                    models.Index(fields=["calendar", "start_time"], name="cal_event_start_idx"),
                    models.Index(fields=["calendar", "end_time"], name="cal_event_end_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("calendar", "google_event_id"),
                        name="calendars_event_calendar_google_event_id_uniq",
                    )
                ],
            },
        ),
    ]
