# Generated by Django 6.0.3 on 2026-04-05 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatTurn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=32,
                    ),
                ),
                (
                    "result_kind",
                    models.CharField(
                        choices=[
                            ("answer", "Answer"),
                            ("clarification", "Clarification"),
                            ("fallback", "Fallback"),
                            ("error", "Error"),
                        ],
                        default="error",
                        max_length=32,
                    ),
                ),
                (
                    "scope_decision",
                    models.CharField(
                        choices=[
                            ("in_scope", "In scope"),
                            ("greeting", "Greeting"),
                            ("out_of_scope", "Out of scope"),
                            ("mutation_request", "Mutation request"),
                            ("ambiguous", "Ambiguous"),
                        ],
                        default="ambiguous",
                        max_length=32,
                    ),
                ),
                (
                    "failure_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("correlation_id", models.CharField(max_length=64, unique=True)),
                ("trace_events", models.JSONField(default=list)),
                ("eval_snapshot", models.JSONField(default=dict)),
                ("provider_metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assistant_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_turns",
                        to="chat.message",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turns",
                        to="chat.chatsession",
                    ),
                ),
                (
                    "user_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="initiated_turns",
                        to="chat.message",
                    ),
                ),
            ],
            options={
                "db_table": "chat_turn",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["session", "created_at"],
                        name="chat_turn_session_created_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="chat_turn_status_created_idx",
                    ),
                ],
            },
        ),
    ]
