# Generated by Django 6.0.3 on 2026-04-06 08:03

import apps.chat.models.action_proposal
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatturn'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(default=apps.chat.models.action_proposal.generate_action_proposal_public_id, max_length=32, unique=True)),
                ('action_type', models.CharField(choices=[('create_event', 'Create event')], max_length=32)),
                ('summary', models.CharField(max_length=255)),
                ('details', models.JSONField(default=dict)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('executing', 'Executing'), ('executed', 'Executed'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('status_detail', models.CharField(blank=True, max_length=255, null=True)),
                ('result_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assistant_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_proposals', to='chat.message')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_proposals', to='chat.chatsession')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_proposals', to='chat.chatturn')),
            ],
            options={
                'db_table': 'chat_action_proposal',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ActionExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('executing', 'Executing'), ('executed', 'Executed'), ('failed', 'Failed')], default='executing', max_length=32)),
                ('result_payload', models.JSONField(blank=True, default=dict)),
                ('failure_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='chat.actionproposal')),
            ],
            options={
                'db_table': 'chat_action_execution',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='actionproposal',
            index=models.Index(fields=['session', 'status'], name='chat_prop_session_status_idx'),
        ),
        migrations.AddIndex(
            model_name='actionproposal',
            index=models.Index(fields=['turn', 'created_at'], name='chat_prop_turn_created_idx'),
        ),
        migrations.AddIndex(
            model_name='actionexecution',
            index=models.Index(fields=['proposal', 'status'], name='chat_exec_prop_status_idx'),
        ),
    ]
