# Generated by Django 6.0.2 on 2026-04-07 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_actionproposal_actionexecution_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatRateLimitConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("singleton_key", models.CharField(default="default", max_length=32, unique=True)),
                ("daily_message_credit_limit", models.PositiveIntegerField(default=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "chat_rate_limit_config",
            },
        ),
        migrations.CreateModel(
            name="DailyMessageCreditUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("usage_date", models.DateField()),
                ("used_credits", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_message_credit_usages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "chat_daily_message_credit_usage",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "usage_date"),
                        name="chat_daily_message_credit_usage_user_usage_date_uniq",
                    )
                ],
            },
        ),
    ]
